name: Deploy Hugo to GitHub Pages
on:
  push:
    branches:
      - master  # Your main branch name
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch submodules if any

      - name: Install Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.92.2/hugo_extended_0.92.2_Linux-64bit.tar.gz
          tar -xzf hugo_extended_0.92.2_Linux-64bit.tar.gz -C /usr/local/bin

      - name: Build site
        run: hugo server -t terminal

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
